baseURL = "http://shreeti.me"
languageCode = "en-us"
title = "Shreeti"
theme = "mediumish-hugo-theme"
summaryLength = 25
copyright = "Shreeti - All rights reserved"
disqusShortname = "shreeti"
googleAnalytics = "UA-143423795-1"