baseURL = "http://shreeti.me"
languageCode = "en-us"
title = "Shreeti"
theme = "mediumish-hugo-theme"
summaryLength = 25
copyright = "Shreeti - All rights reserved"
disqusShortname = "shreeti"
googleAnalytics = "UA-143423795-1"

[params]
  description ="the clean blog!"

[params.author]
  name = "John Doe"
  thumbnail = "/images/jumbotron.jpg"
  description = "Creator of this blog."

[params.index]
  picture = "/images/jumbotron.jpg"
  title = "John Doe"
  subtitle = "I'm a unique placeholder. Working here and there!"
  mdtext = '''Currently trying to get this blog running, still don't know what the blog will be about!\
**This textblock is a demonstration of the mdtext-param.**\
### This is a markdown heading'''
  alertbar = true

[params.social]
  twitter = "shreetisigdel"
  instagram = "shreetisigdel"

